version: '3.8'

services:
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "order", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: product
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "product", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5



  user-service:
    build: ./User-ms
    container_name: user-service
    ports:
      - "8095:8095"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      DB_CONNECTION_IP: user-db
      DB_CONNECTION_PORT: 3306
      DB_CONNECTION_USERNAME: user
      DB_CONNECTION_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  order-service:
    build: ./Order-ms
    container_name: order-service
    ports:
      - "8096:8096"
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      DB_CONNECTION_IP: order-db
      DB_CONNECTION_PORT: 3306
      DB_CONNECTION_USERNAME: order
      DB_CONNECTION_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  product-service:
    build: ./Product-ms
    container_name: product-service
    ports:
      - "8097:8097"
    depends_on:
      product-db:
        condition: service_healthy
    environment:
      DB_CONNECTION_IP: product-db
      DB_CONNECTION_PORT: 3306
      DB_CONNECTION_USERNAME: product
      DB_CONNECTION_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
