spring:
  application:
    name: User-ms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3307}/user_db?createDatabaseIfNotExist=true
    username: ${DB_CONNECTION_USERNAME:user}
    password: ${DB_CONNECTION_PASSWORD:password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.security: DEBUG
    com.neman.userms: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # 24 hours
      refresh-token:
        expiration: 604800000  # 7 days
