# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: neman
    password: neman123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

