spring:
  profiles:
    include:
      - common
      - db
      - logging
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://my-keycloak:8080/realms/microservice-realm
          jwk-set-uri: http://my-keycloak:8080/realms/microservice-realm/protocol/openid-connect/certs

server:
  servlet:
    context-path: /api
  port: 8090

keycloak:
  realm: microservice-realm
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://my-keycloak:8080}
  resource: microservice-client
  public-client: true
  bearer-only: false
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
