spring:
  application:
    name: api-gateway
    version: 1.0.0
    security:
      jwt:
        secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
  show-actuator: true
  enable-native-support: true

server:
  port: 8080
