spring:
  application:
    name: api-gateway
    version: 1.0.0
    security:
      jwt:
        secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:4020
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: http://localhost:4010
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: http://localhost:4030
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        # Swagger UI route
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**,/webjars/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway API
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /product-service/v3/api-docs
        name: Product Service
      - url: /order-service/v3/api-docs
        name: Order Service
  cache:
    disabled: true

