spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-oidc:
            client-id: demo
            client-secret: lFacC7i5yw2l0KwQoycx9WuJryxT0zUu
            scope: openid,profile,email,demo
            redirect-uri: http://localhost:8085/login/oauth2/code/demo
            provider: keycloak-oidc
            client-name: demo
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/demo-app
          jwk-set-uri: http://localhost:8080/auth/realms/demo-app/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        # User service routes
        - id: user-service
          uri: http://user-service:4020
          predicates:
            - Path=/api/v1/users/**

        # Product service routes
        - id: product-service
          uri: http://product-service:4010
          predicates:
            - Path=/api/v1/products/**

        # Order service routes
        - id: order-service
          uri: http://order-service:4030
          predicates:
            - Path=/api/v1/orders/**

server:
  port: 8085

# JWT konfiqurasiyaları
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000 # 1 saat
      refresh-token:
        expiration: 604800000 # 7 gün

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    com.neman.springcloud: DEBUG

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username
